version: 2

sources:
  - name: northwind
    description: Data from Northwind ERP
    database: curso-etl-101
    schema: erp_northwind  
    tables:
      
      - name: orders
        description: '{{ doc("orders_docs") }}'
        columns:
          - name: order_id
            description: Unique ID for this table

      - name: customers
      - name: order_details
      - name: categories
      - name: suppliers
      - name: products